### ISSUE TITLE
Use Case: List tables/columns in database

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#51]
This would have four operations. One to list the tables in the database, the second to list the columns in a given table. The other two would do the same for views.

**Comment by Grauenwolf** [comment]
We should probably do different versions for each of the more popular databases (e.g. MySQL, PostgreSQL, SQLite).

**Comment by Grauenwolf** [comment]
@mikependon @lukevp @mattjcowan @Arnab-Developer 

I just finished a new recipe for this use case. I only added ADO, Dapper, and Chain. If you think this is one that applies to your ORM go ahead and implement it.

**Comment by Arnab-Developer** [comment]
I am analyzing how this can be done with Entity Framework Core.

**Comment by mikependon** [comment]
Thanks @Grauenwolf , sure will add it here. The DbFieldCache is already present in RepoDB since the beginning, and I am yet to expose the [DbTableCache](https://github.com/mikependon/RepoDB/issues/622) story during or after my release for v1.12.5. It is important on the new use-case RepoDB is trying to solve on Dynamic objects.

**Comment by Arnab-Developer** [comment]
I have created a new pull request (#273) to discover tables and columns with EF Core. The pull request is currently in draft mode because I need to update the documents. 

Please review it. If all are ok then I will update the documentation.

**Comment by Arnab-Developer** [comment]
@Grauenwolf updated the document for EF Core. The pull request (#273) is now ready for review.
