### ISSUE TITLE
Interfaces shouldn't be in Recipes.Core

### ISSUE THREAD

**Issue by FransBouma** [Grauenwolf/DotNet-ORM-Cookbook#56]
I have to reference an interface, Recipes.Immutable.IReadOnlyEmployeeClassification. I have to do that from a NS2.0 project (as it's generated) but I can't, because the interface is in a project with tests which targets netcore3.1. 

This isn't really ideal, the interfaces have nothing to do with netcore3.1, they should be separate in a project targeting ns2.0. I now have to hand-write the readonly repo with a handwritten poco while I could have used my generated code and not lift a finger. All this because the readonly repository implements an interface which references an interface in a repo targeting netcore 3.1

Alternatively I could change the target of my ns2.0 repository to netcore3.1, but it still doesn't change the fact the interfaces really should be in a separate project, **or** the tests should be in a separate project. 

(the project is of type 'console application' while it contains interfaces to be referenced by other projects which IMHO is a sign something's off)

**Comment by FransBouma** [comment]
At least the *model* oriented interfaces should be in a separate project. the repository interfaces can stay I think.

**Comment by Grauenwolf** [comment]
What if we just changed Recipes.Core to be a .NET Standard project?

**Comment by Grauenwolf** [comment]
Ok, so MSTest doesn't support .NET Standard. Which means fixing this properly requires #58 to be done first.

**Comment by FransBouma** [comment]
I still think it's best to factor out the interfaces. I changes my projects to be netcoreapp3.1 libraries, so it's not a blocker or anything, it's just IMHO not that clean. With tests it has to be a netcoreapp target I think.

**Comment by Grauenwolf** [comment]
I was mistaken. It was a different package that didn't like .NET Standard, which I was able to remove entirely. `Recipes.Core` is now a .NET Standard 2.0 library.

We'll revisit moving the interfaces on another day. Right now they are use-case specific, and that's not necessarily the right way to do things. So after we have a few more use cases done, I'll look into refactoring all of the model interfaces into their own project.

Another option I'm considering is to import the test code into each project instead of using the library reference. If that works out, I may be able to eliminate most of the model interfaces. But again, I want to get through some more use cases first so we have a better picture of what's needed.

**Comment by Grauenwolf** [comment]
Done
